### ISSUE TITLE
crashes on ctrl+c

### ISSUE THREAD

**Issue by phatlewt** [wiredwiz/FastColoredTextBox#6]
crashes on ctrl+c copy, using WinForms .Net 8 on windows 10 x64.
any workarounds?

Stack trace:

System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Intersect[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at FastColoredTextBoxNS.Text.ExportToRTF.GetRtfDescriptor(IEnumerable`1 styles)
   at FastColoredTextBoxNS.Text.ExportToRTF.Flush(StringBuilder sb, StringBuilder tempSB, IEnumerable`1 currentStyles)
   at FastColoredTextBoxNS.Text.ExportToRTF.GetRtf(TextSelectionRange r)
   at FastColoredTextBoxNS.FastColoredTextBox.OnCreateClipboardData(DataObject data)
   at FastColoredTextBoxNS.FastColoredTextBox.Copy()
   at FastColoredTextBoxNS.FastColoredTextBox.DoAction(FCTBAction action)
   at FastColoredTextBoxNS.FastColoredTextBox.ProcessKey(Keys keyData)
   at FastColoredTextBoxNS.FastColoredTextBox.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at FastColoredTextBoxNS.FastColoredTextBox.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   at Windows.Win32.PInvoke.DispatchMessage(MSG* lpMsg)
   at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)

**Comment by SpirosArk** [comment]
Hello @phatlewt, fixed it locally, can you give me write access in order to push and open a PR?

**Comment by phatlewt** [comment]
Sorry, little bit confused... write access to what? Just to clarify I found and installed your package from nuget (https://www.nuget.org/packages/FCTB-wired) within visual studio 2022, then started using the fctb textbox within a winforms window. Any chance you could update this repo and/or republish the fixed version to nuget? Thank you very much!

**Comment by SpirosArk** [comment]
I must be a coauthor in order to push my branch in order to be merged to this fork later.

If I understand correct you suggest me to open a pr on the nugget package?

**Comment by SpirosArk** [comment]
> rify I found and installed your package fro

In the original nugget package this does not crash, so there is no need to fix it!

**Comment by SpirosArk** [comment]
@wiredwiz since I went and fixed it, could you give me access in order to push my branch on your solution?

**Comment by wiredwiz** [comment]
Sure thing, sorry, saw the notification a little while ago and spaced.  Can you do a pull request?  Happy to merge it in.

**Comment by SpirosArk** [comment]
@wiredwiz no worries, I am trying to push my fix through visual studio in a new branch I created locally and get 403, I think you must make me coauthor to be able to push

![image](https://github.com/user-attachments/assets/b4788eef-8157-4cff-911c-7a9e162640cd)
